fighter:
  mode: "TIME_SCALE"
  damage-expr: "2.5 * (base_dmg + 1.25(sharp_level) + 2.5(other_level) - 0.5(weakness_level)) * (1 + (strength_level * 1.3)) * (1 - base_armor) * ((20 - prot_level) / 20)"
  armor-dmg-expr: "0.2 * (base_dmg + 1.25(sharp_level) + 2.5(other_level) - 0.5(weakness_level)) * (1 + (strength_level * 1.3)) * (.6 + (.4 / (unbr_level + 1)))"
  sword-dmg-expr: "1 / (unbr_level + 1)"
  knockback-expr: "(1 * sprinting) + (1 * knockback_level)"
  
  # time-scale mode
  time-scale-ms: 500
  
  # near-target mode
  attack-range: 4.0 #meters
  attack-cooldown-ms: 500
  attack-runnable-freq: 5

launcher:
  cooldown-update-frequency: 5 #ticks
  launcher-charge-ms: 3000
  potion-speed: 2.0
  potion-radius: 10 # meters (maximum potion radius, if intensity evaluates to <= 0, the entity will not be affected)
  damage-3-multiplier: 0.8
  # variables: air_time (potion air time in ticks), distance_sq (the squared distance to the entity)
  intensity-expr: "(1 + (air_time / 40)) / sqrt(distance_sq) - 0.5"

mage:
  armor-bonus:
    diamond: 0.0
    iron: 1.0
    gold: 2.0
    cloth: 1.0
    chainmail: 3.0
  drain-spell:
    cooldown: 0
    cost: 5
    damage-expr: "1 + ab"
  launch-spell:
    cooldown: 0
    cost: 2
    magnitude-expr: "1.5 + .5ab"
  rupture-spell:
    cooldown: 60000
    cost: 10
  smite-spell:
    cooldown: 500
    cost: 1
    damage-expr: "4 + 2ab"
  snare-spell:
    cooldown: 5000
    cooldown-increase: 5000
    cost: 0
    duration-expr: "60 + 40ab" #ticks

runes:
  magic-damage-reduction: 0.5
  launcher-cooldown-reduction: 0.5
  power-launcher-multiplier: 2
  hunger-regen-ticks: 100
  tenacity-reduction: 0.4
  vanish-inaction-ms: 5000
  vanish-task-ticks: 10
  rage-length-ms: 2000
  rage-speed: 0.3
  rage-task-ticks: 1
  